<a href="https://colab.research.google.com/github/maddygoodro/MIS433/blob/main/Assignment1_python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [1]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? Maddy
Welcome, Maddy!


In [3]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')

print(f)

#Celsius = (Fahrenheit – 32)*5/9
f= int(f)
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 60
60
60F is 15.555555555555555 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [19]:
# complete your program here
c = input('Please enter the temperature in Celsius: ')

print(c)

#Fahrenheit = (Celsius + 32)*5/9
c= int(c)
f = (c + 32) * 5/9

print(f'{c} C is {f} in Fahrenheit. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Celsius: 20
20
20 C is 28.88888888888889 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [10]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')

d= int(d)

if m == 'C':
  f = (d + 32) * 5/9
  print(f'{d}C is {f} in Fahrenheit. ')
elif m == 'F':
  c = (d - 32) * 5/9
  print(f'{d}F is {c} in Celsius. ')

Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 51.111111111111114 in Fahrenheit. 


## Question 2

Have some fun with strings.

In [12]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [13]:
# Find the length of this sentence.
len(sentence)

48

In [14]:
# Convert the whole string to lower case.
sentence.lower()

'talk is cheap. show me the code - linus torvalds'

In [21]:
# Extract a substring from the 10th character from left to the 10th character from right.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"
print(sentence[9:-10])

heap. Show me the code - Linu


In [16]:
# Split the sentence into a list of substrings by space ' '.
print(sentence.split())

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [18]:
# Given the sentence, output a list of words in lowercase (without punctuations).
print(sentence.lower().replace('.','').split())

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', '-', 'linus', 'torvalds']


In [19]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
vowels = 'aeiou'
count = 0
for v in vowels:
    #print(v)
  #make sure sentence is all lower case so that uppercase vowels are counted
    print(v, sentence.lower().count(v))
    count += sentence.lower().count(v)
print(f"The total number of vowels is {count}")

a 3
e 4
i 2
o 3
u 1
The total number of vowels is 13


In [20]:
# Find the positions (indexes) of all vowels in the sentence.
for i in range(len(sentence)):
    if sentence[i] in vowels:
      print(i, sentence[i])

1 a
5 i
10 e
11 a
17 o
21 e
25 e
28 o
30 e
35 i
37 u
41 o
44 a


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [22]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
#empty list
cubes = []

#loop to calculate the first 5 cube numbers
for i in range(5):
    cubes.append(i**3)
print(cubes)


[0, 1, 8, 27, 64]


In [23]:
# Use list comprehension to create the same list

#[ ... ]: Square brackets define the creation of a new list.
#i**3: is the expression that calculates the cube of the variable i (using the exponent operator ** for "to the power of 3").
#for i in range(5): This loop iterates through the numbers 0, 1, 2, 3, and 4. The range(5) function starts at 0 and stops before reaching 5.

cubes = [i**3 for i in range(5)]
print(cubes)


[0, 1, 8, 27, 64]


In [24]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
for i in range(len(sentence)):
    if sentence[i] in vowels:
      print(i, sentence[i])

1 o
3 o
9 e
11 a
14 e
15 e
17 i
22 e
25 e
28 o
31 i
35 a
38 a
41 a
45 o
47 e


In [18]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = input('How many numbers do you want? ')
n = int(n)

# add your code here
if n == 1:
  fibonacci = [0]
elif n == 2:
    fibonacci = [0,1]
elif n > 2:
    fibonacci = [0,1]
    while len(fibonacci) < n:
      fibonacci.append(fibonacci[-1]+ fibonacci[-2])

print(fibonacci)



How many numbers do you want? 10
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [31]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {'Pfizer' : '95', 'Moderna' : '95', 'AstraZeneca' : '72', 'Johnson & Johnson' : '66'}
print(v_dict)

{'Pfizer': '95', 'Moderna': '95', 'AstraZeneca': '72', 'Johnson & Johnson': '66'}


In [33]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v_dict[v])

Which vaccine? Pfizer
95


In [36]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = '91.4'
print(v_dict)

{'Pfizer': '95', 'Moderna': '95', 'AstraZeneca': '72', 'Johnson & Johnson': '66', 'Sputnik V': '91.4'}


In [37]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = '50.38'
print(v_dict)

{'Pfizer': '95', 'Moderna': '95', 'AstraZeneca': '72', 'Johnson & Johnson': '66', 'Sputnik V': '91.4', 'Sinovac': '50.38'}


In [41]:
# Print vaccines with efficacy lower than 90%.
for k,v in v_dict.items():
  if float(v) < 90:
    print(k)

AstraZeneca
Johnson & Johnson
Sinovac


In [43]:
# delete the Sinovac vaccine from the dictionary.
del v_dict['Sinovac']
print(v_dict)

{'Pfizer': '95', 'Moderna': '95', 'AstraZeneca': '72', 'Johnson & Johnson': '66', 'Sputnik V': '91.4'}


In [46]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# Add your code here
for char in sentence:
    if char != ' ':
        ch_dict[char] = ch_dict.get(char, 0) + 1

# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [47]:
import numpy as np

In [48]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [49]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [50]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
    [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
    [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
    [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
    [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
    [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
    [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
    [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
    [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [52]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10, 10))
M.shape
print(M)

[[ 0.92293421 -1.03218454 -0.40644378  0.0847726  -0.56047138 -0.65438757
   0.86785733  0.28518866 -0.55502315 -0.91873763]
 [-0.48824433 -0.13956005  0.54095524  1.35544013  0.05804463 -0.70431388
  -1.79998543 -1.04413241 -0.70843409 -0.16491883]
 [-0.54844574  0.8687309   0.42826119  0.27555872 -2.0986823   0.18041481
  -1.89506589 -1.11087806 -1.11423372  0.18592715]
 [-1.18093708 -0.37266907 -1.1823252   2.43802666  0.65419869  0.58091087
   0.43122452 -1.37426198 -0.53966288  0.60610753]
 [-1.71917638  1.7075904  -0.5379381   0.60701351  0.76638031 -0.15678806
   1.66610423  0.90812535 -0.67880245 -1.10778721]
 [-0.62486527  0.64682253  0.16282998 -0.16994385 -0.72776583 -0.17972564
   0.70288787  0.62307984 -0.75348363  1.16504628]
 [ 0.8878384  -1.28179039 -0.72992635  1.00228822  0.06541061  0.3688644
  -0.40165096  0.69238297  0.2286483  -0.55426645]
 [ 0.04962296  0.796152   -0.9143506   0.82286345 -1.39766694 -0.41582286
   0.49402811  0.37963176 -0.52722027 -0.09691161]
 

In [58]:
# Count the numbers in M with an absolute value greater than 1.
count = np.sum(np.abs(M) > 1)
print(count)

29


In [60]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')

# Input the number of rows (input another integer >= 3)
c = input('column count: ')
r = int(r)
c= int(c)
# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, (r, c))
arr

Row count: 5
column count: 4


array([[18, 17, 18, 19],
       [15, 15, 12, 15],
       [11, 13, 17, 16],
       [19, 12, 19, 13],
       [15, 16, 12, 18]])

In [61]:
# output the element in the first row and the third column
# 0 = 1 and 2= 3 since python sequences start with 0
print(arr[0,2])

18


In [63]:
# output the element in the second row and the last column
print(arr[1,-0])

15


In [64]:
# output the second row of the array
print(arr[1])

[15 15 12 15]


In [67]:
# output the second last row of the array
print(arr[-2])

[19 12 19 13]


In [68]:
# output the second column of the array
print(arr[:,1])

[17 15 13 12 16]


In [69]:
# output the second last column of the array
print(arr[:,-2])

[18 12 17 19 12]


In [71]:
# output the upper-left 3x3 sub-array
print(arr[0:3, 0:3])

[[18 17 18]
 [15 15 12]
 [11 13 17]]


In [73]:
# output the bottom-left 3x3 sub-array
print(arr[-3:, :3])

[[11 13 17]
 [19 12 19]
 [15 16 12]]


In [84]:
# output the upper-right 3x3 sub-array
print(arr[:-2,-3:])

[[17 18 19]
 [15 12 15]
 [13 17 16]]


In [85]:
# output the bottom-right 3x3 sub-array
print(arr[-3:,-3:])

[[13 17 16]
 [12 19 13]
 [16 12 18]]


In [88]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1, 51)
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
A = A.reshape(5, 10)
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [91]:
# add a row [51 ... 60] to A
new_row = np.arange(51, 61)
A = np.vstack((A, new_row))
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [95]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1, A2 = np.vsplit(A, 2)
# The reshape calls are not needed here as vsplit already returns arrays of the correct shape
print("A1:")
print(A1)
print("\nA2:")
print(A2)

A1:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

A2:
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [97]:
# Add 10 to each element of A
A1 = A1 + 10
print(A1)
A2 = A2 + 10
print (A2)

[[21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
[[41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [98]:
# Calculate the square root of each element in A
A1 = np.sqrt(A1)
print(A1)
A2 = np.sqrt(A2)
print(A2)

[[4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
  5.19615242 5.29150262 5.38516481 5.47722558]
 [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
  6.08276253 6.164414   6.244998   6.32455532]
 [6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
  6.8556546  6.92820323 7.         7.07106781]]
[[6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
  6.8556546  6.92820323 7.         7.07106781]
 [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
  7.54983444 7.61577311 7.68114575 7.74596669]
 [7.81024968 7.87400787 7.93725393 8.         8.06225775 8.1240384
  8.18535277 8.24621125 8.30662386 8.36660027]]


In [99]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [101]:
# Print the mean, standard deviation of all numbers in M
print(M.mean())
print(M.std())

-0.13306810076882353
0.958736396860786


In [103]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print(f"Maximum: {np.max(M)}")
print(f"3rd Quartile: {np.percentile(M, 75)}")
print(f"Median: {np.median(M)}")
print(f"1st Quartile: {np.percentile(M, 25)}")
print(f"Minimum: {np.min(M)}")

Maximum: 2.517186714174314
3rd Quartile: 0.587210034509523
Median: -0.1608534436900283
1st Quartile: -0.7541435295788763
Minimum: -2.4382820621045505
